### ISSUE TITLE
broken redirect after login

### ISSUE THREAD

**Issue by neothematrix** [neothematrix/noip-renew#27]
just to report that the script is currently broken due to some changes to noip.com website, I'm working on a fix.
basically, a redirect has been added between the login page and the dynamic hosts page that requires some more code to be added to the script.
I'll try to fix it asap.

**Comment by Angel0ffDeath** [comment]
@neothematrix Do not load login page. Load directly my.noip.com/dynamic-dns. This first will load login page and after that correct page with hosts and will skip redirection. I will have time in the afternoon and will fix it if you didnt

**Comment by Angel0ffDeath** [comment]
@neothematrix Sorry, didnt have time today to fix it. Just tried your script but, it seems it doesnt work. Will try to find some time tomorrow to fix it.

**Comment by peterchs** [comment]
I've made few changes got it working for me:
https://github.com/neothematrix/noip-renew/blob/732387fe6d42b03ca8be4c26d43190fbcc37f3e7/noip-renew.py#L46
TO:
`HOST_URL = "https://www.noip.com/redirect/mynoip?force=true&intended=dynamic-dns"`

After clicking log in I'm checking for 'Sign Out' here - hopefully more resilient way of knowing its logged in correctly rather than just looking for the top banner id.
https://github.com/neothematrix/noip-renew/blob/732387fe6d42b03ca8be4c26d43190fbcc37f3e7/noip-renew.py#L95
TO:
`elem = WebDriverWait(self.browser, 20).until( EC.presence_of_element_located((By.XPATH, "//a[text()='Sign Out']")))`

**Comment by neothematrix** [comment]
thanks @peterchs the HOST_URL change is more elegant than what I was doing, that is, call the /redirect link before opening the dynamic-dns.
Regarding the login check, I'd rather not use XPATH if not necessary, the purpose of checking for the "free-callout" is just to make sure the full page is loaded since the element is close to the end of the html. If login didn't work, the page is completely different anyways and won't contain the "free-callout".

**Comment by peterchs** [comment]
Yea I just see more risk of them changing layout / banner style than removing the ‘Sign Out’ but up to you both work for now..
