### ISSUE TITLE
unclear instructions

### ISSUE THREAD

**Issue by ntzb** [neothematrix/noip-renew#30]
hi, I'm a little bit unclear on how to use this on Debian.
it seems the script doesn't finish successfully?
two packages cannot be installed:
E: Package 'chromium-browser' has no installation candidate
E: Unable to locate package chromium-chromedriver
not sure how to move on from here?

**Comment by Angel0ffDeath** [comment]
Which exactly Debian we are speaking about?

**Comment by ntzb** [comment]
Debian GNU/Linux 11 (bullseye)

**Comment by Angel0ffDeath** [comment]
Ok. I dont have bullseye to test it, but it looks like google repository is missing. 
You can try this:
https://www.itsfoss.net/how-to-install-google-chrome-on-debian-11-bullseye/amp/
Perform steps 1 to 4 to add repository and then run setup.sh again.
If there are some problems post output here for further assistance.

**Comment by ntzb** [comment]
still can't continue with setup.sh. after adding that repo, here's the output:

```
Select an option: 1
  Operating System: Debian GNU/Linux 11 (bullseye)
Installing necessary packages...
Perform apt-get update? (y/n): y
Hit:1 http://ftp.de.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 http://ftp.de.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package chromium-chromedriver
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfile-readbackwards-perl
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  chromium chromium-common
Suggested packages:
  chromium-l10n chromium-shell
The following packages will be upgraded:
  chromium chromium-common chromium-driver
3 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 74.0 MB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 http://security.debian.org/debian-security bullseye-security/main amd64 chromium-driver amd64 103.0.5060.134-1~deb11u1 [5,043 kB]
Get:2 http://security.debian.org/debian-security bullseye-security/main amd64 chromium amd64 103.0.5060.134-1~deb11u1 [64.1 MB]
Get:3 http://security.debian.org/debian-security bullseye-security/main amd64 chromium-common amd64 103.0.5060.134-1~deb11u1 [4,848 kB]
Fetched 74.0 MB in 2s (31.7 MB/s)      
apt-listchanges: Reading changelogs...
(Reading database ... 98853 files and directories currently installed.)
Preparing to unpack .../chromium-driver_103.0.5060.134-1~deb11u1_amd64.deb ...
Unpacking chromium-driver (103.0.5060.134-1~deb11u1) over (103.0.5060.114-1~deb1
1u1) ...
Preparing to unpack .../chromium_103.0.5060.134-1~deb11u1_amd64.deb ...
Unpacking chromium (103.0.5060.134-1~deb11u1) over (103.0.5060.114-1~deb11u1) ..
.
Preparing to unpack .../chromium-common_103.0.5060.134-1~deb11u1_amd64.deb ...
Unpacking chromium-common (103.0.5060.134-1~deb11u1) over (103.0.5060.114-1~deb1
1u1) ...
Setting up chromium-common (103.0.5060.134-1~deb11u1) ...
Setting up chromium (103.0.5060.134-1~deb11u1) ...
Setting up chromium-driver (103.0.5060.134-1~deb11u1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.4-2) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cron is already the newest version (3.0pl1-137).
The following package was automatically installed and is no longer required:
  libfile-readbackwards-perl
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package chromium-browser is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'chromium-browser' has no installation candidate
```

**Comment by Angel0ffDeath** [comment]
@ntzb Ok. Perfect. It seems problem is solved :)

**Comment by ntzb** [comment]
right, here we go:
https://github.com/neothematrix/noip-renew/pull/32

**Comment by nitzan-blink** [comment]
@Angel0ffDeath I had two more issues, and I'm wondering if somehow I was the only one:
1. the script would not run because /var/log/noip-renew/ntzb was owned by root, and not writeable by the user
2. the scheduler (noip-renew-sk.sh) runs crontab as sudo, but fails since it needs a password as input: `ntzb : a password is required ; PWD=/var/log/noip-renew/ntzb ; USER=root ; COMMAND=/usr/bin/crontab -u ntzb -l`

I solved them both (for the first one, had to chown, for the second one, had to add no sudo password for crontab commands)

**Comment by Angel0ffDeath** [comment]
Open an new issue for that. For the first – you need to delete /var/log/noip-renew/ntzb and to run setup.sh again. Then with the same user run the script which will do the rest. For the second – you are correct – the script uses sudo to create cronjob, all though if it is the same user you don’t need sudo to create this. The user which I use is added to sudoers and I don’t have this issue  Sent from Mail for Windows From: nitzan-blinkSent: 09 август 2022 г. 9:23To: neothematrix/noip-renewCc: Angel0ffDeath; MentionSubject: Re: [neothematrix/noip-renew] unclear instructions (Issue ***@***.*** I had two more issues, and I'm wondering if somehow I was the only one:the script would not run because /var/log/noip-renew/ntzb was owned by root, and not writeable by the userthe scheduler (noip-renew-sk.sh) runs crontab as sudo, but fails since it needs a password as input: ntzb : a password is required ; PWD=/var/log/noip-renew/ntzb ; USER=root ; COMMAND=/usr/bin/crontab -u ntzb -lI solved them both (for the first one, had to chown, for the second one, had to add no sudo password for crontab commands)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
